### ISSUE TITLE
npm version is out of date

### ISSUE THREAD

**Issue by jemartti** [AfterShip/aftership-nodejs#3]
I've noticed that aftership-nodejs is up to tagged release v4.1.0 on Github; however, the version on npm is still v3.0.1. Could you guys possibly publish a new version to npm?

This would help out all those api users who got the v3 deprecation email the other day.

**Comment by Atinux** [comment]
:+1: 

Please `npm publish` @Bossa573 @teddychan

**Comment by Atinux** [comment]
@jemartti you can do this in your package.json to have the last version meanwhile:
```json
{
  "dependencies": {
     "aftership": "https://github.com/AfterShip/aftership-nodejs/tarball/master"
  }
}
```

**Comment by jemartti** [comment]
@Atinux: Yea, I ended up with something similar:
```
"aftership": "git://github.com/AfterShip/aftership-nodejs#4.1.0"
```

**Comment by teddychan** [comment]
if you use package.json
```
{
    "dependencies": {
        "aftership": "latest"
    }
}

```

you should get the latest `4.1.1` now
